//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyAnalysis.Infrastructure.Cache {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyAnalysis.Infrastructure.Cache.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE cache_index(
        ///[Id] INTEGER PRIMARY KEY ASC NOT NULL, 
        ///[Url] NVARCHAR(512) NOT NULL, 
        ///[Path] NVARCHAR(512) NOT NULL, 
        ///[CreatedOn] DATETIME NOT NULL,
        ///[ExpiredOn] DATETIME NOT NULL,
        ///[Hash] NVARCHAR(128) NOT NULL
        ///).
        /// </summary>
        internal static string CREATE_INDEX_TABLE {
            get {
                return ResourceManager.GetString("CREATE_INDEX_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM cache_index WHERE [Hash] = @Hash.
        /// </summary>
        internal static string DELETE_INDEX_BY_HASH {
            get {
                return ResourceManager.GetString("DELETE_INDEX_BY_HASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO cache_index(
        ///[Url], 
        ///[Path], 
        ///[CreatedOn],
        ///[ExpiredOn],
        ///[Hash]
        ///)  
        ///VALUES(
        ///@Url,
        ///@Path,
        ///@CreatedOn,
        ///@ExpiredOn,
        ///@Hash).
        /// </summary>
        internal static string INSERT_INTO_CACHE_INDEX {
            get {
                return ResourceManager.GetString("INSERT_INTO_CACHE_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///[Url], 
        ///[Path], 
        ///[CreatedOn],
        ///[ExpiredOn],
        ///[Hash]
        ///FROM cache_index.
        /// </summary>
        internal static string SELECT_INDEX_ALL {
            get {
                return ResourceManager.GetString("SELECT_INDEX_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///[Url], 
        ///[Path], 
        ///[CreatedOn],
        ///[ExpiredOn],
        ///[Hash]
        ///FROM cache_index
        ///WHERE [Hash] = @Hash.
        /// </summary>
        internal static string SELECT_INDEX_BY_HASH {
            get {
                return ResourceManager.GetString("SELECT_INDEX_BY_HASH", resourceCulture);
            }
        }
    }
}
